name: "Chasing"
description: "What is really important?"
author: "leezh"
url: 'https://leezh76.github.io' 
# baseurl: ''


markdown: kramdown
excerpt_separator: "<!-- more -->"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 7
paginate_path: /page-:num


#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

